using System.Numerics;
using System.Text.Json;
using SoulsFormats;

internal static class BossObjectTests
{
    internal static void Run()
    {
        int assertions = 0;
        void Need(bool value, string message) { assertions++; if (!value) throw new Exception(message); }
        void Refused(Action action, string fragment) { try { action(); throw new Exception("expected object refusal: " + fragment); } catch (InvalidDataException error) { Need(error.Message.Contains(fragment), error.Message); } }
        void SetShorts(MSBB.Part.Object item, string property, short[] values) => typeof(MSBB.Part.Object).BaseType!.GetProperty(property)!.GetSetMethod(true)!.Invoke(item, [values]);
        string root = Path.Combine(Path.GetTempPath(), "bb-boss-object-" + Guid.NewGuid().ToString("N")); Directory.CreateDirectory(root);
        try {
            string source = Path.Combine(root, "source"), destination = Path.Combine(root, "destination"), plan = Path.Combine(root, "plan.json"); Directory.CreateDirectory(source); Directory.CreateDirectory(destination);
            string sourcePath = Path.Combine(source, "m23_00_00_00.msb"), destinationPath = Path.Combine(destination, "m26_00_00_00.msb");
            var donor = new MSBB(); donor.Models.Enemies.Add(new MSBB.Model.Enemy { Name = "c9000", SibPath = "" }); donor.Models.Objects.Add(new MSBB.Model.Object { Name = "o269800", SibPath = "N:\\obj\\o269800.sib" });
            donor.Parts.Enemies.Add(new MSBB.Part.Enemy { Name = "source_anchor", EntityID = 100, ModelName = "c9000", Position = new Vector3(10, 0, 10), Rotation = new Vector3(0, 15, 0) });
            var marker = new MSBB.Part.Object { Name = "source_marker", Description = "marker", EntityID = 101, ModelName = "o269800", SibPath = "", InstanceID = 7, Position = new Vector3(12, 1, 13), Rotation = new Vector3(10, 30, 20), Scale = new Vector3(2, 3, 4), UnkE04 = 14, UnkE05 = 15, UnkE06 = 16, UnkE07 = 17, LanternID = 18, LodParamID = 19, UnkE0E = 20, UnkE0F = 21, BreakTerm = 2, NetSyncType = 3, CollisionFilter = true, SetMainObjStructureBooleans = true };
            marker.DrawGroups[0] = 99; marker.DispGroups[0] = 98; marker.BackreadGroups[0] = 97; marker.Gparam.LightSetID = 5; marker.Gparam.FogParamID = 6; marker.Gparam.LightScatteringID = 7; marker.Gparam.EnvMapID = 8; SetShorts(marker, nameof(MSBB.Part.Object.AnimIDs), [1,2,3,4]); SetShorts(marker, nameof(MSBB.Part.Object.ModelSfxParamRelativeIDs), [5,6,7,8]); donor.Parts.Objects.Add(marker); donor.Write(sourcePath);
            var target = new MSBB(); target.Models.Enemies.Add(new MSBB.Model.Enemy { Name = "c1000", SibPath = "" }); target.Models.Objects.Add(new MSBB.Model.Object { Name = "oexisting", SibPath = "" });
            var anchor = new MSBB.Part.Enemy { Name = "destination_anchor", EntityID = 200, ModelName = "c1000", Position = new Vector3(50, 0, 40), Rotation = new Vector3(0, 105, 0) }; anchor.DrawGroups[0] = 7; anchor.DispGroups[0] = 8; anchor.BackreadGroups[0] = 9; target.Parts.Enemies.Add(anchor);
            target.Parts.Objects.Add(new MSBB.Part.Object { Name = "existing_object", EntityID = 205, ModelName = "oexisting" }); target.Regions.Regions.Add(new MSBB.Region { Name = "existing_region", EntityID = 210 }); target.Events.Generators.Add(new MSBB.Event.Generator { Name = "existing_event", EventID = 300, EntityID = 301 }); target.Write(destinationPath);
            var sourceRead = MSBB.Read(sourcePath); var destinationRead = MSBB.Read(destinationPath); var readMarker = sourceRead.Parts.Objects.Single(item => item.Name == "source_marker"); var sourceAnchor = sourceRead.Parts.Enemies.Single(); var destinationAnchor = destinationRead.Parts.Enemies.Single(); var existing = destinationRead.Parts.Objects.Single(item => item.Name == "existing_object");
            var addition = new { source_map = "m23_00_00_00", source_part = "source_marker", source_entity_id = 101, source_provenance = new { format = "bb-boss-object-pin-v1", part_sha256 = BossObjectTransplant.Fingerprint("m23_00_00_00", sourceRead, readMarker) }, source_anchor_part = "source_anchor", source_anchor_provenance = new { format = "bb-boss-actor-pin-v1", part_sha256 = BossActorTransplant.Fingerprint("m23_00_00_00", sourceAnchor) }, destination_map = "m26_00_00_00", destination_part = "destination_marker", destination_entity_id = 300, destination_anchor_part = "destination_anchor", destination_anchor_provenance = new { format = "bb-boss-actor-pin-v1", part_sha256 = BossActorTransplant.Fingerprint("m26_00_00_00", destinationAnchor) } };
            void WritePlan(object item) => File.WriteAllText(plan, JsonSerializer.Serialize(new { boss_object_additions = new[] { item } }));
            WritePlan(addition); string output = Path.Combine(root, "output"); var applied = BossObjectTransplant.Apply(plan, source, destination, output, false); Need(applied.Count == 1 && applied[0].DestinationPart == "destination_marker", "one reviewed object applied"); BossObjectTransplant.VerifyFinal(applied, destination, output);
            var written = MSBB.Read(Path.Combine(output, "m26_00_00_00.msb")); var clone = written.Parts.Objects.Single(item => item.Name == "destination_marker");
            Need(clone.EntityID == 300 && clone.ModelName == "o269800" && written.Models.Objects.Single(item => item.Name == "o269800").SibPath == "N:\\obj\\o269800.sib", "object model resource retained");
            Need(Vector3.Distance(clone.Position, new Vector3(53, 1, 38)) < .001f && MathF.Abs(clone.Rotation.Y - 120) < .001f && clone.Scale == new Vector3(2,3,4), "object uses degree-relative anchor transform");
            Need(clone.DrawGroups[0] == 7 && clone.DispGroups[0] == 8 && clone.BackreadGroups[0] == 9, "object loading groups remain destination-owned");
            Need(clone.AnimIDs.SequenceEqual(new short[] {1,2,3,4}) && clone.ModelSfxParamRelativeIDs.SequenceEqual(new short[] {5,6,7,8}) && clone.Gparam.EnvMapID == 8 && clone.BreakTerm == 2 && clone.NetSyncType == 3 && clone.UnkE04 == 14 && clone.LodParamID == 19 && clone.UnkE0F == 21, "object native type data retained");
            Need(BossObjectTransplant.Fingerprint("m26_00_00_00", written, written.Parts.Objects.Single(item => item.Name == "existing_object")) == BossObjectTransplant.Fingerprint("m26_00_00_00", destinationRead, existing), "original destination object unchanged");
            var sourceBytes = File.ReadAllBytes(sourcePath);
            var destinationBytes = File.ReadAllBytes(destinationPath);
            var drift = MSBB.Read(sourcePath); drift.Parts.Objects.Single().Position += Vector3.UnitX; drift.Write(sourcePath); Refused(() => BossObjectTransplant.Apply(plan, source, destination, Path.Combine(root, "source-drift"), false), "object provenance pin drift"); File.WriteAllBytes(sourcePath, sourceBytes);
            var anchorDrift = MSBB.Read(destinationPath); anchorDrift.Parts.Enemies.Single().Position += Vector3.UnitX; anchorDrift.Write(destinationPath); Refused(() => BossObjectTransplant.Apply(plan, source, destination, Path.Combine(root, "anchor-drift"), false), "destination object anchor provenance pin drift"); File.WriteAllBytes(destinationPath, destinationBytes);
            var nameCollision = new { addition.source_map, addition.source_part, addition.source_entity_id, addition.source_provenance, addition.source_anchor_part, addition.source_anchor_provenance, addition.destination_map, destination_part = "existing_object", addition.destination_entity_id, addition.destination_anchor_part, addition.destination_anchor_provenance }; WritePlan(nameCollision); Refused(() => BossObjectTransplant.Apply(plan, source, destination, Path.Combine(root, "name-collision"), false), "object destination Part already exists");
            var regionCollision = new { addition.source_map, addition.source_part, addition.source_entity_id, addition.source_provenance, addition.source_anchor_part, addition.source_anchor_provenance, addition.destination_map, destination_part = "region-collision", destination_entity_id = 210, addition.destination_anchor_part, addition.destination_anchor_provenance }; WritePlan(regionCollision); Refused(() => BossObjectTransplant.Apply(plan, source, destination, Path.Combine(root, "region-collision"), false), "object destination entity ID already exists");
            var eventCollision = new { addition.source_map, addition.source_part, addition.source_entity_id, addition.source_provenance, addition.source_anchor_part, addition.source_anchor_provenance, addition.destination_map, destination_part = "event-collision", destination_entity_id = 301, addition.destination_anchor_part, addition.destination_anchor_provenance }; WritePlan(eventCollision); Refused(() => BossObjectTransplant.Apply(plan, source, destination, Path.Combine(root, "event-collision"), false), "object destination entity ID already exists");
            var collisionMap = MSBB.Read(sourcePath); collisionMap.Parts.Collisions.Add(new MSBB.Part.Collision { Name = "source_collision" }); collisionMap.Parts.Objects.Single().CollisionName = "source_collision"; collisionMap.Write(sourcePath); var collisionRead = MSBB.Read(sourcePath); var collisionObject = collisionRead.Parts.Objects.Single(); var collisionAddition = new { addition.source_map, addition.source_part, addition.source_entity_id, source_provenance = new { format = "bb-boss-object-pin-v1", part_sha256 = BossObjectTransplant.Fingerprint("m23_00_00_00", collisionRead, collisionObject) }, addition.source_anchor_part, addition.source_anchor_provenance, addition.destination_map, destination_part = "foreign-collision", destination_entity_id = 302, addition.destination_anchor_part, addition.destination_anchor_provenance }; WritePlan(collisionAddition); Refused(() => BossObjectTransplant.Apply(plan, source, destination, Path.Combine(root, "foreign-collision"), false), "object source collision mapping unsupported"); File.WriteAllBytes(sourcePath, sourceBytes);
            File.WriteAllText(plan, JsonSerializer.Serialize(new { format = "bb-enemizer-plan-v2", dry_run = true, swaps = Array.Empty<object>(), boss_object_additions = new[] { addition } })); Refused(() => MapTransplant.Run(plan, destination, Path.Combine(root, "nonboss")), "boss object additions require --boss-encounters");
            Console.WriteLine($"PASS: {assertions} boss object transplant assertions");
        } finally { if (Path.GetDirectoryName(root) != Path.GetTempPath().TrimEnd(Path.DirectorySeparatorChar) || !Path.GetFileName(root).StartsWith("bb-boss-object-")) throw new Exception("unsafe cleanup path"); Directory.Delete(root, true); }
    }
}
